version: "3.9"

services:
  # React Frontend - Standalone
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: focusforge-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000/api/v1}
      - REACT_APP_WEBSOCKET_URL=${REACT_APP_WEBSOCKET_URL:-ws://localhost:8000/ws}
      - REACT_APP_ENV=${NODE_ENV:-development}
      - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP:-true}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-true}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/build
    networks:
      - frontend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  frontend-network:
    driver: bridge
