version: "3.9"

services:
  # Mobile Development Environment
  mobile-dev:
    build:
      context: ./mobile
      dockerfile: Dockerfile.dev
    container_name: focusforge-mobile-dev
    ports:
      - "3001:3000"  # Flutter web dev server
      - "8080:8080"  # Flutter web build server
    environment:
      - FLUTTER_API_URL=${FLUTTER_API_URL:-http://localhost:8000/api/v1}
      - FLUTTER_WEBSOCKET_URL=${FLUTTER_WEBSOCKET_URL:-ws://localhost:8000/ws}
      - FLUTTER_ENV=${FLUTTER_ENV:-development}
    volumes:
      - ./mobile:/app
      - flutter_pub_cache:/root/.pub-cache
    networks:
      - mobile-network
    restart: unless-stopped
    working_dir: /app
    command: ["flutter", "run", "-d", "web-server", "--web-port=3000", "--web-hostname=0.0.0.0"]

volumes:
  flutter_pub_cache:

networks:
  mobile-network:
    driver: bridge
